[project]
name = "semantickernel-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "semantic-kernel>=1.29.0",
]
